ChildrenDatabase/ChildrenDatabase.MVC/Models/About.cs
namespace ChildrenDatabase.MVC.Models
{
    public class About
    {
        public string? Title { get; set; }
        public string? Description { get; set; }
        public List<string> Tags { get; set; } = new List<string>();
    }
}

ChildrenDatabase/ChildrenDatabase.MVC/Models/Child.cs
namespace ChildrenDatabase.MVC.Models
{
    public class Child
    {
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
    }
}

ChildrenDatabase/ChildrenDatabase.MVC/Models/ErrorViewModel.cs
namespace ChildrenDatabase.MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ChildrenDatabase/ChildrenDatabase.MVC/Controllers/ChildrenDatabaseController.cs
using ChildrenDatabase.Application.ChildrenDatabase;
using ChildrenDatabase.Application.ChildrenDatabase.Commands.CreateChildrenDatabase;
using ChildrenDatabase.Application.ChildrenDatabase.Queries.GetAllChildrenDatabases;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;

namespace ChildrenDatabase.MVC.Controllers
{
    public class ChildrenDatabaseController : Controller 
    {
        private readonly IMediator _mediator;

        public ChildrenDatabaseController(IMediator mediator) 
        {
            _mediator = mediator;
        }

        public async Task <IActionResult> Index()
        {
            var childrenDatabases = await _mediator.Send(new GetAllChildrenDatabasesQuery());
            return View(childrenDatabases);
        }
        public IActionResult Create () 
        { 
            return View();
        }

        public IActionResult Details()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(CreateChildrenDatabaseCommand command)
        {
           if(!ModelState.IsValid)
            {
                return View(command);
            }
            await _mediator.Send(command);
           return RedirectToAction(nameof(Create));
        }
    }
}

ChildrenDatabase/ChildrenDatabase.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ChildrenDatabase.MVC.Models;

namespace ChildrenDatabase.MVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        var model = new List<Child>()
        {
            new Child ()
            {
                FirstName = "Tomek",
                LastName = "Kot"
            }
        };
        return View(model);
    }

    public IActionResult About()
    {
        var model = new About()
        {
            Title = "Preschool children",
            Description = "Database of children attending our prechool",
            Tags = new List<string> { "children", "preschool", "kindergarten" }
        };
        return View(model);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ChildrenDatabase/ChildrenDatabase.MVC/Views/ChildrenDatabase/Create.cshtml
@using ChildrenDatabase.Application.ChildrenDatabase
@using ChildrenDatabase.Application.ChildrenDatabase.Commands.CreateChildrenDatabase

@model CreateChildrenDatabaseCommand  

 <h1>Add new child</h1>
 
<hr />

<div class="row">
    <div class="col-md-4">
        <form action="/ChildrenDatabase/Create" method="post">
            <div class="form-group mb-3">
                <label class="control-label" asp-for="Name">Name</label>
                <input class="form-control" type="text" asp-for="Name"></input>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="Surname">Surname</label>
                <input class="form-control" type="text" asp-for="Surname"></input>
                <span asp-validation-for="Surname" class="text-danger"></span>

            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="Age">Age</label>
                <input class="form-control" type="text" asp-for="Age"></input>
            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="Address">Address</label>
                <input class="form-control" type="text" asp-for="Address"></input>
            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="ParentPhoneNumber">Parent phone number</label>
                <input class="form-control" type="text" asp-for="ParentPhoneNumber"></input>
                <span asp-validation-for="ParentPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="DateOfBirth">Date of birth</label>
                <input class="form-control" type="text" asp-for="DateOfBirth"></input>
            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="HealthInfo">Health Info</label>
                <input class="form-control" type="text"  asp-for="HealthInfo"></input>
            </div>

            <div class="form-group mb-3 ">
                <input type="submit" value="Create" class="btn btn-primary">
            </div>
                       
        </form>
    </div>
</div>


@section Scripts  {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ChildrenDatabase/ChildrenDatabase.MVC/Views/ChildrenDatabase/Index.cshtml
@model IEnumerable<ChildrenDatabase.Application.ChildrenDatabase.ChildrenDatabaseDto>

@{
    ViewData["Title"] = "Children Database";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HealthInfo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ParentPhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HealthInfo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParentPhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

ChildrenDatabase/ChildrenDatabase.MVC/Views/Home/About.cshtml
@model About

<h1>@Model.Title</h1>
<h2>@Model.Description</h2>

<p>Tagi:</p>
<ul>
    @foreach (var tag in Model.Tags) {
        <li>@tag</li>
    }
</ul>

ChildrenDatabase/ChildrenDatabase.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Preschool Children Database</h1>
    

ChildrenDatabase/ChildrenDatabase.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChildrenDatabase.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChildrenDatabase.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChildrenDatabase</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ChildrenDatabase" asp-action="Create">Create</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ChildrenDatabase" asp-action="Index">Children List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ChildrenDatabase - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>